Use init.d file based on lumberjack's default

diff --git a/templates/etc/init.d/lumberjack.erb b/templates/etc/init.d/lumberjack.erb
--- a/templates/etc/init.d/lumberjack.erb
+++ b/templates/etc/init.d/lumberjack.erb
@@ -1,69 +1,93 @@
-#!/bin/bash
-# Lumberjack daemon
-# chkconfig: 345 20 80
-# description: lumberjack daemon
-# processname: lumberjack
+### BEGIN INIT INFO
+# Provides:          Lumberjack
+# Required-Start:    $remote_fs $syslog
+# Required-Stop:     $remote_fs $syslog
+# Default-Start:     2 3 4 5
+# Default-Stop:      0 1 6
+# Short-Description: Lumberjack lightweight log shipping
+# Description:       Lumberjack lightweight log shipping
+### END INIT INFO
 
-DAEMON_PATH="<%= @installdir %>"
-DAEMON="bin/lumberjack.sh"
-OUTPUT=""
+# Author: Jordan Sissel <jordan.sissel@dreamhost.com>
 
-DAEMONOPTS="-config=<%= @fullconfig %> <% if @cpuprofile %> -cpuprofile=<%= @cpuprofile  %>  <% end %> -idle-flush-time=<%= @idle_flush_time %> -log-to-syslog=<%= @log_to_syslog %> -spool-size=<%= @spool_size %>"
-
-NAME="lumberjack"
-DESC="Lumberjack"
+# PATH should only include /usr/* if it runs after the mountnfs.sh script
+PATH=/sbin:/usr/sbin:/bin:/usr/bin
+DESC="log shipper"
+NAME=lumberjack
+DAEMON=/opt/lumberjack/bin/lumberjack
+DAEMON_ARGS="-config=<%= @fullconfig %> <% if @cpuprofile %> -cpuprofile=<%= @cpuprofile  %>  <% end %> -idle-flush-time=<%= @idle_flush_time %> -log-to-syslog=<%= @log_to_syslog %> -spool-size=<%= @spool_size %>"
 PIDFILE=/var/run/$NAME.pid
 SCRIPTNAME=/etc/init.d/$NAME
 
+COMMAND="cd /var/run; exec $DAEMON $DAEMON_ARGS"
+
+[ -r /etc/default/$NAME ] && . /etc/default/$NAME
+. /lib/init/vars.sh
+. /lib/lsb/init-functions
+
+do_start() {
+  # Skip if it's already running
+  start-stop-daemon --start --quiet --pidfile $PIDFILE --exec /bin/sh --test > /dev/null || return 1
+
+  cd /var/run
+  # Actually start it now.
+  start-stop-daemon --start --quiet --make-pidfile --background \
+    --pidfile $PIDFILE --exec /bin/sh -- -c "$COMMAND" || return 2
+}
+
+do_stop()
+{
+  start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE
+  RETVAL="$?"
+  [ "$RETVAL" = 2 ] && return 2
+  start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
+  [ "$?" = 2 ] && return 2
+  rm -f $PIDFILE
+  return "$RETVAL"
+}
+
 case "$1" in
-start)
-	printf "%-50s" "Starting $NAME..."
-	cd $DAEMON_PATH
-	PID=`$DAEMON $DAEMONOPTS > /dev/null 2>&1 & echo $!`
-	#echo "Saving PID" $PID " to " $PIDFILE
-        if [ -z $PID ]; then
-            printf "%s\n" "Fail"
-        else
-            echo $PID > $PIDFILE
-            printf "%s\n" "Ok"
-        fi
-;;
-status)
-        printf "%-50s" "Checking $NAME..."
-        if [ -f $PIDFILE ]; then
-            PID=`cat $PIDFILE`
-            if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
-                printf "%s\n" "Process dead but pidfile exists"
-                exit 1
-            else
-                echo "Running"
-                exit 0
-            fi
-        else
-            printf "%s\n" "Service not running"
-            exit 1
-        fi
-;;
-stop)
-        printf "%-50s" "Stopping $NAME"
-            PID=`cat $PIDFILE`
-            cd $DAEMON_PATH
-        if [ -f $PIDFILE ]; then
-            kill -HUP $PID
-            printf "%s\n" "Ok"
-            rm -f $PIDFILE
-        else
-            printf "%s\n" "pidfile not found"
-        fi
-;;
-
-restart)
-  	$0 stop
-  	$0 start
-;;
-
-*)
-        echo "Usage: $0 {status|start|stop|restart}"
-        exit 1
+  start)
+    [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+    do_start
+    case "$?" in
+      0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+      2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+    esac
+    ;;
+  stop)
+    [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+    do_stop
+    case "$?" in
+      0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+      2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+    esac
+    ;;
+  status)
+    status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+    ;;
+  restart|force-reload)
+    log_daemon_msg "Restarting $DESC" "$NAME"
+    do_stop
+    case "$?" in
+      0|1)
+        do_start
+        case "$?" in
+          0) log_end_msg 0 ;;
+          1) log_end_msg 1 ;; # Old process is still running
+          *) log_end_msg 1 ;; # Failed to start
+        esac
+      ;;
+      *)
+        # Failed to stop
+        log_end_msg 1
+      ;;
+    esac
+    ;;
+  *)
+    echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
+    exit 3
+    ;;
 esac
 
+:
